name: Deploy to HTTP Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        server: [http_server_1, http_server_2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/flask:latest

    - name: Deploy Docker container
      run: |
        ssh user@${{ matrix.server }} 'docker run -d --name app -p 80:5000 -e REDIS_HOST=redis -e DB_NAME=mydatabase -e DB_PASSWORD=password -e DB_USER=user -e DB_HOST=db ${{ secrets.DOCKER_USERNAME }}/flask:latest'